name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for better analysis

      - name: Debug Environment Variables
        run: env | sort  # Debugging step to check if necessary variables exist

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=ex-arbete
            -Dsonar.sources=src
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.exclusions=**/test/**,**/*.md
